######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 27 21:44:09 2007
######################################################################

CONFIG -= qt
TARGET = proto
LIBS += -lmenu -lpanel -lform -lncurses
TEMPLATE = app
TARGET = proto
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += proto.c
